- name: Build inside Docker (ARM64 cross-compile)
  run: |
    set -euxo pipefail
    echo "Repo layout (top 2 levels):"
    find . -maxdepth 2 -mindepth 1 -printf "%y %p\n" | sort
    echo "CMakeLists I can see:"
    find . -name CMakeLists.txt -printf "%p\n" | sort

    docker build -t coriolis-arm64 .
    CID=$(docker create coriolis-arm64)
    docker cp "$CID":/src/build ./build || true
    docker logs "$CID" --tail 200 || true
    docker rm "$CID" || true
