name: Build for Raspberry Pi (ARM64)

on:
  push:
    branches: [ "main", "pi-build" ]
  workflow_dispatch:

jobs:
  arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build inside Docker (ARM64 cross-compile)
        run: |
          set -euxo pipefail
          echo "Top-level tree:"
          ls -la
          echo "Searching for CMakeLists:"
          find . -maxdepth 3 -name CMakeLists.txt -print | sort
          docker build -t coriolis-arm64 .
          CID=$(docker create coriolis-arm64)
          mkdir -p build
          # Pull out artifacts (if build succeeded) and helpful logs (even if it failed)
          docker cp "$CID":/src/build ./build || true
          echo "---- Build tree on container (if present) ----"
          docker exec "$CID" bash -lc 'set -e; [ -d /src/build ] && find /src/build -maxdepth 2 -type f | sort | tail -n 100 || true' || true
          echo "---- CMake error/output logs (if present) ----"
          docker cp "$CID":/src/build/CMakeFiles/CMakeError.log ./CMakeError.log || true
          docker cp "$CID":/src/build/CMakeFiles/CMakeOutput.log ./CMakeOutput.log || true
          echo "---- Last 200 container logs ----"
          docker logs "$CID" --tail 200 || true
          docker rm "$CID" || true

      - name: Upload build (and any logs)
        uses: actions/upload-artifact@v4
        with:
          name: coriolis-arm64
          path: |
            build
            CMakeError.log
            CMakeOutput.log
